version: '3'
services:
  trfuniverse.fpm:
    build:
      context: .
      target: fpm_server
    image: trfuniverse/fpm_server
    environment:
      APP_DEBUG: "false"
      APP_KEY: "base64:voAFAEAk+LjyUyA6rf8mXXo4wr9LrKu/obePKnZzK9M="
      APP_URL: "http://localhost"
      FRONTEND_URL: "http://localhost:3000"
      DISABLE_RATE_LIMIT: "true"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "trfuniverse"
      DB_USERNAME: "trfuniverse"
      DB_PASSWORD: "trfuniverse"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
    volumes:
      - 'trfuniverse-private-cache:/opt/apps/trfuniverse/storage/app/cache'
      - 'trfuniverse-public:/opt/apps/trfuniverse/storage/app/public'
    networks:
      - trfuniverse-network
  trfuniverse.web:
    build:
      context: .
      target: web_server
    image: trfuniverse/web_server
    ports:
      - '8080:80'
    environment:
      FPM_HOST: "trfuniverse.fpm:9000"
      APP_KEY: "base64:voAFAEAk+LjyUyA6rf8mXXo4wr9LrKu/obePKnZzK9M="
      APP_DEBUG: "false"
      APP_URL: "http://localhost"
      FRONTEND_URL: "http://localhost:3000"
      DISABLE_RATE_LIMIT: "true"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "trfuniverse"
      DB_USERNAME: "trfuniverse"
      DB_PASSWORD: "trfuniverse"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
    volumes:
      - 'trfuniverse-private-cache:/opt/apps/trfuniverse/storage/app/cache'
      - 'trfuniverse-public:/opt/apps/trfuniverse/storage/app/public'
    networks:
      - trfuniverse-network
  trfuniverse.cron:
    build:
      context: .
      target: cron
    image: trfuniverse/cron
    volumes:
      - 'trfuniverse-private-cache:/opt/apps/trfuniverse/storage/app/cache'
      - 'trfuniverse-public:/opt/apps/trfuniverse/storage/app/public'
    networks:
      - trfuniverse-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "trfuniverse"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "trfuniverse"
      MYSQL_USER: "trfuniverse"
      MYSQL_PASSWORD: "trfuniverse"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'trfuniverse-mysql:/var/lib/mysql'
    networks:
      - trfuniverse-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-ptrfuniverse" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'trfuniverse-redis:/data'
    networks:
      - trfuniverse-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  trfuniverse-network:
volumes:
  trfuniverse-mysql:
    driver: local
  trfuniverse-redis:
    driver: local
  trfuniverse-private-cache:
    driver: local
  trfuniverse-public:
    driver: local
